zytrip/config/routes.rb
Rails.application.routes.draw do
  resources :additional_informations
  resources :surveys
  get 'trips_research/preferences_poll', to: "trips_research#preferences_poll", as: "preferences_poll"
  get 'trips_research/results'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  resources :trips
  resources :preferences, only: [:new, :create]
  resources :topics, only: [:new, :create]
  resources :companies, only: [:new, :create]
  resources :services, only: [:new, :create]
  resources :reviews, only: [:new, :create]
  resources :surveys, only: [:new, :create]
  resources :additional_informations, only: [:new, :create]

  resources :friendships, only: [:destroy]
  get "/friendships/add_friend", to: "friendships#add_friend"
  get "/friendships/delete_friend", to: "friendships#delete_friend"

  get "/policies/privacy", to: "policies#privacy", as: 'privacy'
  get "/policies/terms_of_use", to: "policies#terms_of_use", as: 'terms_of_use'
  get "landing/about", to: "landing#about", as: 'about'
  get "landing/guide", to: "landing#guide", as: 'guide'

  devise_for :users

  devise_scope :users do
    get '/users/:id/profile', to: 'users#profile', as: 'users_profile'
    get '/users/:id/update_aditional_info', to: 'users#update_aditional_info', as: 'users_profile_aditional_info'
  end

  devise_scope :users do
    get '/users/:id/test', to: 'users#test', as: 'users_test'
  end

  root to: 'landing#home'

  namespace :admin do
    controller :admin do
      resources :trips do
        collection { post :import }
      end

      resources :agencies do
        collection { post :import }
      end

      resources :preferences do
        collection { post :import }
      end

      resources :services do
        collection { post :import }
      end

      resources :topics do
        collection { post :import }
      end
      
      resources :companies do
        collection { post :import }
      end
      
      resources :users do
        collection { post :import }
      end

      resources :reviews do
        collection { post :import }
      end

      resources :surveys do
        collection { post :import }
      end

      resources :friendships, only: [:new, :create, :index, :destroy] do
        collection { post :import }
      end

      resources :additional_informations do
        collection { post :import}
      end

      get "/dashboards/dashboard", to: "dashboards#dashboard"
      get "/dashboards/testing", to: "dashboards#testing"
    end
  end
end

zytrip/app/models/service.rb
class Service < ApplicationRecord
	belongs_to :preference

	#Exporta todos los datos en un csv
  	def self.to_csv(fields = column_names, options = {})
  		CSV.generate(options) do |csv|
  			csv << fields
  			all.each do |service|
  				csv << service.attributes.values_at(*fields)
  			end
  		end
  	end

  	#Importa los datos desde un csv
  	def self.import
  		path = Rails.root + "app/csv/services.csv"
  		CSV.foreach(path, headers: true) do |row|
  			service_hash = row.to_hash
			if Service.where("id" => service_hash['id']).exists?
  				service = Service.find_by(id: service_hash['id'])
  			else
  				service = Service.create!(service_hash)
  			end
  			service.update(service_hash)
  		end
  	end
end

zytrip/app/controllers/admin/services_controller.rb
class Admin::ServicesController < ApplicationController

  def index
    unless current_user and current_user.admin?
      redirect_to root_path, error: "You don't belong there"
    end
    
    @services = Service.all

    respond_to do |format|
      format.html
      format.csv { send_data @services.to_csv(['id', 'preference_id', 'lodging', 'gastronomy', 'activities']) }
    end
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.save
    redirect_to admin_services_path
  end

  def destroy
    @service = Service.find_by(id: params[:id])
    redirect_to admin_services_path unless @service
    @service.destroy
    redirect_to admin_services_path
  end

  def edit
    @service = Service.find_by(id: params[:id])
    redirect_to admin_services_path unless @service
  end

  def update
    @service = Service.find_by(id: params[:id])
    @service.update(service_params)
    redirect_to admin_services_path
  end

  def import
    Service.import()
    redirect_to admin_services_path
  end

  def service_params
    params.require(:service).permit(:preference_id, :lodging, :gastronomy, :activities)
  end
end

zytrip/app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def new
    @service = Service.new
  end

  def create
    @preference = Preference.last
    @service = Service.new(service_params.merge(preference_id: @preference.id))
    @service.save
    redirect_to trips_path
  end

  private
  
  def service_params
    params.require(:service).permit(:lodging, :gastronomy, :activities)
  end
end

zytrip/app/views/admin/services/_service_form_fields.html.erb
<div class="row">
	<div class="col-md-12 mb-3">
		<%= f.label(:preference_id, "Preferencia", class:"create-edit-form-label") %>
		<%= f.select(:preference_id, options_for_select(Preference.ids)) %>
	</div>
</div>

<div class="row">

	<div class="col-3 mb-3">
		<%= f.label(:lodging, "Alojamiento", class:"create-edit-form-label") %>
		<%= f.check_box :lodging, class:"create-edit-form-checkbox", autofocus: true %>
	</div>

	<div class="col-3 mb-3">
		<%= f.label(:gastronomy, "Gastronomía", class:"create-edit-form-label") %>
		<%= f.check_box :gastronomy, class:"create-edit-form-checkbox", autofocus: true %>
	</div>

	<div class="col-3 mb-3">
		<%= f.label(:activities, "Actividades", class:"create-edit-form-label") %>
		<%= f.check_box :activities, class:"create-edit-form-checkbox", autofocus: true %>
	</div>
</div>

zytrip/app/views/admin/services/edit.html.erb
<%= render "layouts/sidebar" %>

<section>
  <div class="create-edit-styled-box">
    <h2 class="create-edit-header">Editar Servicio</h2>
    <%= form_for(@service, url: admin_service_path(@service)) do |f| %>
      <%= render partial: "service_form_fields", :locals => {:f => f} %>
      <div class="actions-btns">
        <div class="row">
          <div class="col-lg-6 col-md-12 col-sm-12 text-center create-edit-form-cancel-btn">
                <%= link_to "Volver", :back, class: "create-edit-form-cancel-link" %>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 text-center ">
                <%= f.submit "Guardar cambios", class: "create-edit-form-submit-btn" %>
            </div>
          </div>
        </div>
        <% end %>
    </div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "admin" %>
<% end %>

zytrip/app/views/admin/services/index.html.erb
<%= render "layouts/sidebar" %>

<section>
  <div class="admin-main" id="users">

    <div class="admin-new-panel">
      <div class="row ">
        <div class="col-6 admin-model-title">
          <strong>Servicios</strong>
        </div>

        <div class="col-6">
          <%= form_tag import_admin_services_path, multipart: true, class: "form-inline" do %>
            <div class="row">
              <div class="col import-form-btn text-center">
                <%= link_to "Añadir servicio", new_admin_service_path, class: "import-form-btn-link" %>
              </div>
              <div class="col import-form-btn text-center">
                <%= link_to "Exportar CSV", admin_services_path(format: :csv), class: "import-form-btn-link" %>
              </div>
              <div class="col text-center">
                <%= submit_tag "Importar servicios", class:"import-form-submit-btn" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <table class="admin-model-table">
      <thead>
        <tr>
          <th>ID Preferencia</th>
          <th>Alojamiento</th>
          <th>Gastronomía</th>
          <th>Actividades</th>
          <th>Administración</th>
        </tr>
      </thead>

      <tbody>
        <% @services.each do |service| %>
          <tr>
            <td><%= service.preference_id %></td>
            <td><%= service.lodging %></td>
            <td><%= service.gastronomy %></td>
            <td><%= service.activities %></td>
            <td>
              <div class="row justify-content-center">
                <div class="col-2">
                  <%= link_to edit_admin_service_path(service), title:"Editar" do %>
                    <i class="fas fa-briefcase"></i>
                  <% end %>
                </div>

                <div class="col-2">
                  <%= button_to admin_service_path(service), method: :delete, class:"admin-delete-button", title:"Eliminar" do %> 
                    <i class="fas fa-briefcase admin-delete"></i>
                  <% end %>
                </div>
              </div>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "admin" %>
<% end %>

zytrip/app/views/admin/services/new.html.erb
<%= render "layouts/sidebar" %>
<section>
  <div class="create-edit-styled-box">
    <h2 class="create-edit-header">Crear Servicio</h2>
    <%= form_for(@service, url: admin_services_path(@service)) do |f| %>
      <%= render partial: "service_form_fields", :locals => {:f => f} %>
      <div class="actions-btns">
        <div class="row">
          <div class="col-lg-6 col-md-12 col-sm-12 text-center create-edit-form-cancel-btn">
                <%= link_to "Volver", :back, class: "create-edit-form-cancel-link" %>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 text-center ">
                <%= f.submit "Crear", class: "create-edit-form-submit-btn" %>
            </div>
          </div>
        </div>
        <% end %>
    </div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "admin" %>
<% end %>