zytrip/config/routes.rb
Rails.application.routes.draw do
  resources :additional_informations
  resources :surveys
  get 'trips_research/preferences_poll', to: "trips_research#preferences_poll", as: "preferences_poll"
  get 'trips_research/results'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  resources :trips
  resources :preferences, only: [:new, :create]
  resources :topics, only: [:new, :create]
  resources :companies, only: [:new, :create]
  resources :services, only: [:new, :create]
  resources :reviews, only: [:new, :create]
  resources :surveys, only: [:new, :create]
  resources :additional_informations, only: [:new, :create]

  resources :friendships, only: [:destroy]
  get "/friendships/add_friend", to: "friendships#add_friend"
  get "/friendships/delete_friend", to: "friendships#delete_friend"

  get "/policies/privacy", to: "policies#privacy", as: 'privacy'
  get "/policies/terms_of_use", to: "policies#terms_of_use", as: 'terms_of_use'
  get "landing/about", to: "landing#about", as: 'about'
  get "landing/guide", to: "landing#guide", as: 'guide'

  devise_for :users

  devise_scope :users do
    get '/users/:id/profile', to: 'users#profile', as: 'users_profile'
    get '/users/:id/update_aditional_info', to: 'users#update_aditional_info', as: 'users_profile_aditional_info'
  end

  devise_scope :users do
    get '/users/:id/test', to: 'users#test', as: 'users_test'
  end

  root to: 'landing#home'

  namespace :admin do
    controller :admin do
      resources :trips do
        collection { post :import }
      end

      resources :agencies do
        collection { post :import }
      end

      resources :preferences do
        collection { post :import }
      end

      resources :services do
        collection { post :import }
      end

      resources :topics do
        collection { post :import }
      end
      
      resources :companies do
        collection { post :import }
      end
      
      resources :users do
        collection { post :import }
      end

      resources :reviews do
        collection { post :import }
      end

      resources :surveys do
        collection { post :import }
      end

      resources :friendships, only: [:new, :create, :index, :destroy] do
        collection { post :import }
      end

      resources :additional_informations do
        collection { post :import}
      end

      get "/dashboards/dashboard", to: "dashboards#dashboard"
      get "/dashboards/testing", to: "dashboards#testing"
    end
  end
end

zytrip/app/models/preference.rb
class Preference < ApplicationRecord

	##############################
	# Preferences Relations
	##############################
	has_one :service, dependent: :destroy
	has_one :company, dependent: :destroy
	has_one :topic, dependent: :destroy
	belongs_to :trip

	##############################
	#Preferences enums
	##############################

	enum destination: {
		spain: 0,
		europe: 1,
		africa: 2,
		america: 3,
		asia: 4
	}, _prefix: true

	enum budget: {
		low: 0,
		medium: 1,
		high: 2,
		expensive: 3
	}, _prefix: true

	enum duration: {
		short: 0,
		ordinary: 1,
		long: 2,
		overlong: 3
	}, _prefix: true

	################################################################
	# Helper functions for enums
	# --------------------------
	# -> By using _prefix: true you can access to helpers like this:
	#
	#    preference.destination_spain?  ----> destination == 'spain'
	# 
	# -> This helpers will be used in the survey controller
	################################################################
	

	#######################################
	# Helper functions for associations
	#######################################

	# ----- Services ----- #

	def remarkable_gastronomy?
		return true if self.service.gastronomy == true
		return false
	end

	def remarkable_lodging?
		return true if self.service.lodging == true
		return false
	end

	def remarkable_activities?
		return true if self.service.activities == true
		return false
	end

	# ----- Companies ----- #

	def family_as_company?
		return true if self.company.family == true
		return false
	end

	def partner_as_company?
		return true if self.company.romantic == true
		return false
	end

	def friends_as_company?
		return true if self.company.friends == true
		return false
	end

	def alone_as_company?
		return true if self.company.alone == true
		return false
	end

	def new_people_as_company?
		return true if self.company.people == true
		return false
	end

	# ----- Topic ----- #

	def beach_as_main_topic?
		return true if self.topic.beach == true
		return false
	end

	def nature_as_main_topic?
		return true if self.topic.nature == true
		return false
	end

	def tourism_as_main_topic?
		return true if self.topic.tourism == true
		return false
	end

	def relax_as_main_topic?
		return true if self.topic.relax == true
		return false
	end

	#Exporta todos los datos en un csv
  	def self.to_csv(fields = column_names, options = {})
  		CSV.generate(options) do |csv|
  			csv << fields
  			all.each do |preference|
  				csv << preference.attributes.values_at(*fields)
  			end
  		end
  	end

  	#Importa los datos desde un csv
  	def self.import
  		path = Rails.root + "app/csv/preferences.csv"
  		CSV.foreach(path, headers: true) do |row|
  			preference_hash = row.to_hash
			if Preference.where("id" => preference_hash['id']).exists?
  				preference = Preference.find_by(id: preference_hash['id'])
  			else
  				preference = Preference.create!(preference_hash)
  			end
  			preference.update(preference_hash)
  		end
  	end
end

zytrip/app/controllers/admin/preferences_controller.rb
class Admin::PreferencesController < ApplicationController

  def index
    unless current_user and current_user.admin?
      redirect_to root_path, error: "You don't belong there"
    end
    
    @preferences = Preference.all

    respond_to do |format|
      format.html
      format.csv { send_data @preferences.to_csv(['id', 'trip_id', 'destination', 'budget', 'duration']) }
    end
  end

  def new
    @preference = Preference.new
  end

  def create
    @preference = Preference.new(preference_params)
    @preference.save
    redirect_to admin_preferences_path
  end

  def destroy
    @preference = Preference.find_by(id: params[:id])
    redirect_to admin_preferences_path unless @preference
    @preference.destroy
    redirect_to admin_preferences_path
  end

  def edit
    @preference = Preference.find_by(id: params[:id])
    redirect_to admin_preferences_path unless @preference
  end

  def update
    @preference = Preference.find_by(id: params[:id])
    @preference.update(preference_params)
    redirect_to admin_preferences_path
  end

  def import
    Preference.import()
    redirect_to admin_preferences_path
  end

  def preference_params
    params.require(:preference).permit(:trip_id, :destination, :budget, :duration)
  end
end

zytrip/app/controllers/concerns/preferences_controller.rb
class PreferencesController < ApplicationController
	def new
    	@preference = Preference.new
  	end

  	def create
  		@trip = Trip.last

  		if preference_params[:destination] == 0
  			@destination = 0
  		elsif preference_params[:destination] == "Europa"
  			@destination = 1
  		elsif preference_params[:destination] == "África"
  			@destination = 2
  		elsif preference_params[:destination] == "América"
  			@destination = 3
  		else
  			@destination = 4
  		end

  		if preference_params[:duration] == "Menos de 3 días"
  			@duration = 0
  		elsif preference_params[:duration] == "Entre 3 y 5 días"
  			@duration = 1
  		elsif preference_params[:duration] == "Entre 5 y 7 días"
  			@duration = 2
  		else
  			@duration = 3
  		end

  		if @trip.price < 500
  			@preference = Preference.new(trip_id: @trip.id, budget: 0, destination: @destination, duration: @duration)
  			#@preference = Preference.new(preference_params.merge(trip_id: @trip.id, budget: 0))
    	elsif (@trip.price >= 500 && @trip.price < 1000)
    		@preference = Preference.new(trip_id: @trip.id, budget: 1, destination: @destination, duration: @duration)
    		#@preference = Preference.new(preference_params.merge(trip_id: @trip.id, budget: 1))
    	elsif (@trip.price >= 1000 && @trip.price < 1500)
    		@preference = Preference.new(trip_id: @trip.id, budget: 2, destination: @destination, duration: @duration)
    		#@preference = Preference.new(preference_params.merge(trip_id: @trip.id, budget: 2))
    	else
    		@preference = Preference.new(trip_id: @trip.id, budget: 3, destination: @destination, duration: @duration)
    		#@preference = Preference.new(preference_params.merge(trip_id: @trip.id, budget: 3))
    	end

    	@preference.save
    	redirect_to new_topic_path(preference_id: @preference.id)
  	end

  	def destroy
    	@preference = Preference.find_by(id: params[:id])
    	redirect_to preferences_path unless @preference
    	@preference.destroy
    	redirect_to preferences_path
  	end

  	private

  	def preference_params
    	params.require(:preference).permit(:destination, :duration)
  	end

end

zytrip/app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
	def new
    	@preference = Preference.new
  	end

  	def create
  		@trip = Trip.last

  		if preference_params[:destination] == "Rutas Ibéricas"
  			@destination = 0
  		elsif preference_params[:destination] == "Europa"
  			@destination = 1
  		elsif preference_params[:destination] == "África"
  			@destination = 2
  		elsif preference_params[:destination] == "América"
  			@destination = 3
  		else
  			@destination = 4
  		end

  		if preference_params[:duration] == "Menos de 3 días"
  			@duration = 0
  		elsif preference_params[:duration] == "Entre 3 y 5 días"
  			@duration = 1
  		elsif preference_params[:duration] == "Entre 5 y 7 días"
  			@duration = 2
  		else
  			@duration = 3
  		end

  		@new_pref_id = (Preference.all.size + 1)
  		if @trip.price < 500
  			@preference = Preference.new(id: @new_pref_id, trip_id: @trip.id, budget: 0, destination: @destination, duration: @duration)
  			#@preference = Preference.new(preference_params.merge(trip_id: @trip.id, budget: 0))
    	elsif (@trip.price >= 500 && @trip.price < 1000)
    		@preference = Preference.new(id: @new_pref_id, trip_id: @trip.id, budget: 1, destination: @destination, duration: @duration)
    		#@preference = Preference.new(preference_params.merge(trip_id: @trip.id, budget: 1))
    	elsif (@trip.price >= 1000 && @trip.price < 1500)
    		@preference = Preference.new(id: @new_pref_id, trip_id: @trip.id, budget: 2, destination: @destination, duration: @duration)
    		#@preference = Preference.new(preference_params.merge(trip_id: @trip.id, budget: 2))
    	else
    		@preference = Preference.new(id: @new_pref_id, trip_id: @trip.id, budget: 3, destination: @destination, duration: @duration)
    		#@preference = Preference.new(preference_params.merge(trip_id: @trip.id, budget: 3))
    	end

    	@preference.save
    	redirect_to new_topic_path(preference_id: @preference.id)
  	end

  	private

  	def preference_params
    	params.require(:preference).permit(:destination, :duration)
  	end

end

zytrip/app/views/admin/preferences/_preference_form_fields.html.erb
<div class="row">
	<div class="col-md-12 mb-3">
		<%= f.label(:trip_id, "Viaje", class:"create-edit-form-label") %>
		<%= f.collection_select(:trip_id, Trip.all, :id, :title, {include_blank: 'Seleccionar Viaje'}, required: true, 
		class:"create-edit-form-input") %>
	</div>
</div>

<div class="row">

	<div class="col-3 mb-3">
		<%= f.label(:destination, "Destino", class:"create-edit-form-label") %>
		<%= f.select(:destination, options_for_select(Preference.destinations.keys)) %>
	</div>

	<div class="col-3 mb-3">
		<%= f.label(:budget, "Presupuesto", class:"create-edit-form-label") %>
		<%= f.select(:budget, options_for_select(Preference.budgets.keys)) %>
	</div>

	<div class="col-3 mb-3">
		<%= f.label(:duration, "Duración", class:"create-edit-form-label") %>
		<%= f.select(:duration, options_for_select(Preference.durations.keys)) %>
	</div>
</div>

zytrip/app/views/admin/preferences/edit.html.erb
<%= render "layouts/sidebar" %>

<section>
  <div class="create-edit-styled-box">
    <h2 class="create-edit-header">Editar Preferencia</h2>
    <%= form_for(@preference, url: admin_preference_path(@preference)) do |f| %>
      <%= render partial: "preference_form_fields", :locals => {:f => f} %>
      <div class="actions-btns">
        <div class="row">
          <div class="col-lg-6 col-md-12 col-sm-12 text-center create-edit-form-cancel-btn">
                <%= link_to "Volver", :back, class: "create-edit-form-cancel-link" %>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 text-center ">
                <%= f.submit "Guardar cambios", class: "create-edit-form-submit-btn" %>
            </div>
          </div>
        </div>
        <% end %>
    </div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "admin" %>
<% end %>

zytrip/app/views/admin/preferences/index.html.erb
<%= render "layouts/sidebar" %>

<section>
  <div class="admin-main" id="users">

    <div class="admin-new-panel">
      <div class="row ">
        <div class="col-6 admin-model-title">
          <strong>Preferencias</strong>
        </div>

        <div class="col-6">
          <%= form_tag import_admin_preferences_path, multipart: true, class: "form-inline" do %>
            <div class="row">
              <div class="col import-form-btn text-center">
                <%= link_to "Añadir preferencia", new_admin_preference_path, class: "import-form-btn-link" %>
              </div>
              <div class="col import-form-btn text-center">
                <%= link_to "Exportar CSV", admin_preferences_path(format: :csv), class: "import-form-btn-link" %>
              </div>
              <div class="col text-center">
                <%= submit_tag "Importar preferencias", class:"import-form-submit-btn" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <table class="admin-model-table">
      <thead>
        <tr>
          <th>ID Viaje</th>
          <th>Destino</th>
          <th>Presupuesto</th>
          <th>Duración</th>
          <th>Administración</th>
        </tr>
      </thead>

      <tbody>
        <% @preferences.each do |preference| %>
          <tr>
            <td><%= preference.trip_id %></td>
            <td><%= preference.destination %></td>
            <td><%= preference.budget %></td>
            <td><%= preference.duration %></td>
            <td>
              <div class="row justify-content-center">
                <div class="col-2">
                  <%= link_to edit_admin_preference_path(preference), title:"Editar" do %>
                    <i class="fas fa-briefcase"></i>
                  <% end %>
                </div>

                <div class="col-2">
                  <%= button_to admin_preference_path(preference), method: :delete, class:"admin-delete-button", title:"Eliminar" do %> 
                    <i class="fas fa-briefcase admin-delete"></i>
                  <% end %>
                </div>
              </div>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "admin" %>
<% end %>

zytrip/app/views/admin/preferences/new.html.erb
<%= render "layouts/sidebar" %>
<section>
  <div class="create-edit-styled-box">
    <h2 class="create-edit-header">Crear Preferencia</h2>
    <%= form_for(@preference, url: admin_preferences_path(@preference)) do |f| %>
      <%= render partial: "preference_form_fields", :locals => {:f => f} %>
      <div class="actions-btns">
        <div class="row">
          <div class="col-lg-6 col-md-12 col-sm-12 text-center create-edit-form-cancel-btn">
                <%= link_to "Volver", :back, class: "create-edit-form-cancel-link" %>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 text-center ">
                <%= f.submit "Crear", class: "create-edit-form-submit-btn" %>
            </div>
          </div>
        </div>
        <% end %>
    </div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "admin" %>
<% end %>