zytrip/config/routes.rb
Rails.application.routes.draw do
  resources :additional_informations
  resources :surveys
  get 'trips_research/preferences_poll', to: "trips_research#preferences_poll", as: "preferences_poll"
  get 'trips_research/results'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  resources :trips
  resources :preferences, only: [:new, :create]
  resources :topics, only: [:new, :create]
  resources :companies, only: [:new, :create]
  resources :services, only: [:new, :create]
  resources :reviews, only: [:new, :create]
  resources :surveys, only: [:new, :create]
  resources :additional_informations, only: [:new, :create]

  resources :friendships, only: [:destroy]
  get "/friendships/add_friend", to: "friendships#add_friend"
  get "/friendships/delete_friend", to: "friendships#delete_friend"

  get "/policies/privacy", to: "policies#privacy", as: 'privacy'
  get "/policies/terms_of_use", to: "policies#terms_of_use", as: 'terms_of_use'
  get "landing/about", to: "landing#about", as: 'about'
  get "landing/guide", to: "landing#guide", as: 'guide'

  devise_for :users

  devise_scope :users do
    get '/users/:id/profile', to: 'users#profile', as: 'users_profile'
    get '/users/:id/update_aditional_info', to: 'users#update_aditional_info', as: 'users_profile_aditional_info'
  end

  devise_scope :users do
    get '/users/:id/test', to: 'users#test', as: 'users_test'
  end

  root to: 'landing#home'

  namespace :admin do
    controller :admin do
      resources :trips do
        collection { post :import }
      end

      resources :agencies do
        collection { post :import }
      end

      resources :preferences do
        collection { post :import }
      end

      resources :services do
        collection { post :import }
      end

      resources :topics do
        collection { post :import }
      end
      
      resources :companies do
        collection { post :import }
      end
      
      resources :users do
        collection { post :import }
      end

      resources :reviews do
        collection { post :import }
      end

      resources :surveys do
        collection { post :import }
      end

      resources :friendships, only: [:new, :create, :index, :destroy] do
        collection { post :import }
      end

      resources :additional_informations do
        collection { post :import}
      end

      get "/dashboards/dashboard", to: "dashboards#dashboard"
      get "/dashboards/testing", to: "dashboards#testing"
    end
  end
end

zytrip/app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

zytrip/app/views/layouts/_error.html.erb
<section>
	<div class="container-fluid">
		<div class="bd-callout bd-callout-info">
			<h4 class="error">Ups, ha ocurrido un error no esperado!</h4>

			<br><p class="error-info">Parece que ha intentado acceder a una vista con acceso restringido y no dispone de los permisos necesarios, contacte con nosotros si el error no se resuelve</p>
		</div>
	</div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "main" %>
<% end %>

zytrip/app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="row justify-content-md-center footer-columns">
		<div class="col col-lg-3 footer-section">
			<div class="row justify-content-md-center footer-logo">
				<div class="col col-lg-2">
					<%= image_tag "local/zytrip-transparent-footer-2.png" %>
				</div>

				<div class="col col-lg-3">
					<p class="footer-logo-name">Zytrip</p>
				</div>
			</div>
		</div>

		<div class="col col-lg-3 footer-section">
			<ul class="footer-list">
				<li class="footer-list-item"><i class="fas fa-map-marker-alt"></i>Universidad Autónoma Madrid</li>
				<li class="footer-list-item"><i class="fas fa-envelope"></i>miguel.manzanom@estudiante.uam.es</li>
				<li class="footer-list-item"><i class="fab fa-github"></i>MiguelManzanoUAM/Zytrip</li>
			</ul>
		</div>

		<div class="col col-lg-3 footer-section">
			<text class="footer-about-title text-center">Acerca de Zytrip</text>
			<p class="footer-about">Proyecto de fin de grado basado en el desarrollo e implementación de un sistema de recomendaciones mixto utilizando el framework Ruby on Rails</p>
		</div>
	</div>

	<hr>
	<div class="row">
		<div class="col-4"></div>
		<div class="col-4">
			<p class="footer-copyright-line">2022-2023 Zytrip <text class="footer-copyright-line-links"><%= link_to "Términos de uso", terms_of_use_path, class:"footer-copyright-line-link" %><%= link_to "Política de Privacidad", privacy_path, class:"footer-copyright-line-link"%></text></p>
		</div>
		<div class="col-4"></div>
	</div>
</div>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "main" %>
<% end %>

zytrip/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag "local/zytrip-transparent-footer-2.png", class:"header-logo" %> Zytrip
    <% end %> 

    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to 'Nuestros viajes', trips_path, class: "nav-link header-link" %>
      </li>

      <li class="nav-item">
        <%= link_to 'Acerca de Zytrip', about_path, class: "nav-link header-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Guía y preguntas frecuentes', guide_path, class: "nav-link header-link" %>
      </li>
    </ul>
  </div>

  <% if session[:theme] == "light" %>
    <%= link_to root_path(theme: "dark") do %>
      <i class="fas fa-moon" style="color: #aea7b0;"></i>
    <% end %>
  <% else %>
    <%= link_to root_path(theme: "light") do %>
      <i class="fas fa-sun" style="color: #e8d247;"></i>
    <% end %>
  <% end %>

  <div class="d-flex align-items-center" style="margin-right: 2%; margin-left: 1%;">
    <ul class="navbar-nav">
      <% if user_signed_in?%>
        <% if current_user.admin == true %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Administrador
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
              <li>
                <%= link_to 'Admin dashboard', admin_dashboards_dashboard_path, class: 'dropdown-item' %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= button_to 'Salir', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </li>
            </ul>
          </li>

        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
              <li>
                <%= link_to 'Mi perfil', users_profile_path(current_user), class: 'dropdown-item' %>
              </li>
              <li>
                <%= link_to 'Crear Viaje', new_trip_path, class: 'dropdown-item' %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= button_to 'Salir', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </li>
            </ul>
          </li>

        <% end %>

      <% else %>
        <form class="d-flex">
          <li class="nav-item">
            <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
            
          </li>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
        </form>

      <% end %>
    </ul>
  </div>
</nav>

zytrip/app/views/layouts/_sidebar.html.erb
<section class="sidebar">
  <div class="sidebar-title-container">
    <%= link_to 'Zytrip', root_path, class: 'sidebar-title' %>
  </div>

  <hr>
  <p class="sidebar-section-title">Pruebas</p>
  <hr>

  <div class="sidebar-menu">
    <ul class="sidebar-list">
      
      <li class="sidebar-item">
        <%= link_to admin_dashboards_testing_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt"> Testing</strong>
        <% end %>
      </li>

      <li class="sidebar-item">
        <%= link_to admin_dashboards_dashboard_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt">Estadísticas</strong>
        <% end %>
      </li>
      
    </ul>

    <hr>
    <p class="sidebar-section-title">Administración</p>
    <hr>

    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to admin_users_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt">Usuarios</strong>
        <% end %>
      </li>

      <li class="sidebar-item">
        <%= link_to admin_trips_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt"> Viajes</strong>
        <% end %>
      </li>

      <li class="sidebar-item">
        <%= link_to admin_reviews_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt"> Reviews</strong>
        <% end %>
      </li>

      <li class="sidebar-item">
        <%= link_to admin_surveys_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt"> Encuestas</strong>
        <% end %>
      </li>

      <li class="sidebar-item">
        <%= link_to admin_preferences_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt"> Preferencias</strong>
        <% end %>
      </li>

      <li class="sidebar-item">
        <%= link_to admin_services_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt"> Servicios</strong>
        <% end %>
      </li>

      <li class="sidebar-item">
        <%= link_to admin_topics_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt"> Temáticas</strong>
        <% end %>
      </li>

      <li class="sidebar-item">
        <%= link_to admin_companies_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt"> Compañías</strong>
        <% end %>
      </li>

      <li class="sidebar-item">
        <%= link_to admin_friendships_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt"> Amistades</strong>
        <% end %>
      </li>

      <li class="sidebar-item">
        <%= link_to admin_additional_informations_path, class: 'sidebar-nav-link' do %>
          <strong class="sidebar-nav-opt"> Inf.Adicional</strong>
        <% end %>
      </li>
    </ul>
  </div>

  <hr>
  <p class="sidebar-section-title">Usuario</p>
  <hr>

  <div class="sidebar-footer text-center">
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fas fa-user-tie rounded-circle me-2"></i>
        <strong>Administrador</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1" style="">
        <li>
          <%= button_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        </li>
      </ul>
    </div>
  </div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "main" %>
<% end %>

zytrip/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zytrip</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>