zytrip/config/routes.rb
Rails.application.routes.draw do
  resources :additional_informations
  resources :surveys
  get 'trips_research/preferences_poll', to: "trips_research#preferences_poll", as: "preferences_poll"
  get 'trips_research/results'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  resources :trips
  resources :preferences, only: [:new, :create]
  resources :topics, only: [:new, :create]
  resources :companies, only: [:new, :create]
  resources :services, only: [:new, :create]
  resources :reviews, only: [:new, :create]
  resources :surveys, only: [:new, :create]
  resources :additional_informations, only: [:new, :create]

  resources :friendships, only: [:destroy]
  get "/friendships/add_friend", to: "friendships#add_friend"
  get "/friendships/delete_friend", to: "friendships#delete_friend"

  get "/policies/privacy", to: "policies#privacy", as: 'privacy'
  get "/policies/terms_of_use", to: "policies#terms_of_use", as: 'terms_of_use'
  get "landing/about", to: "landing#about", as: 'about'
  get "landing/guide", to: "landing#guide", as: 'guide'

  devise_for :users

  devise_scope :users do
    get '/users/:id/profile', to: 'users#profile', as: 'users_profile'
    get '/users/:id/update_aditional_info', to: 'users#update_aditional_info', as: 'users_profile_aditional_info'
  end

  devise_scope :users do
    get '/users/:id/test', to: 'users#test', as: 'users_test'
  end

  root to: 'landing#home'

  namespace :admin do
    controller :admin do
      resources :trips do
        collection { post :import }
      end

      resources :agencies do
        collection { post :import }
      end

      resources :preferences do
        collection { post :import }
      end

      resources :services do
        collection { post :import }
      end

      resources :topics do
        collection { post :import }
      end
      
      resources :companies do
        collection { post :import }
      end
      
      resources :users do
        collection { post :import }
      end

      resources :reviews do
        collection { post :import }
      end

      resources :surveys do
        collection { post :import }
      end

      resources :friendships, only: [:new, :create, :index, :destroy] do
        collection { post :import }
      end

      resources :additional_informations do
        collection { post :import}
      end

      get "/dashboards/dashboard", to: "dashboards#dashboard"
      get "/dashboards/testing", to: "dashboards#testing"
    end
  end
end

zytrip/app/models/additional_information.rb
class AdditionalInformation < ApplicationRecord
	belongs_to :user

	validate :validate_additional_info

	#####################################################
	# Validaciones
	#####################################################
	def validate_additional_info

		if instagram_nickname && instagram_nickname.length > 16
		  errors.add :instagram_nickname, 'introduce un usuario más corto (máximo 15 caracteres)'
		end

		if phone_number
			if (phone_number.length > 1) && !(phone_number =~ /^[0-9]{9,12}/)
		  		errors.add :phone_number, 'Introduzca un nº teléfono válido'
		  	end
		end

		if slogan && slogan.length > 30
		  errors.add :slogan, 'slogan demasiado largo (máximo 30 caracteres)'
		end

		if description && description.length > 250
		  errors.add :description, 'descripción demasiado extensa (máximo 250 caracteres)'
		end
	end

	def self.valid_phone_number(number)
		if !(number =~ /^\+(?:[0-9]●?){6,14}[0-9]$/)
		  return false
		end

		return true
	end

	#Exporta todos los datos en un csv
  	def self.to_csv(fields = column_names, options = {})
  		CSV.generate(options) do |csv|
  			csv << fields
  			all.each do |additional_information|
  				csv << additional_information.attributes.values_at(*fields)
  			end
  		end
  	end

  	#Importa los datos desde un csv
  	def self.import
  		path = Rails.root + "app/csv/additional_informations.csv"
  		CSV.foreach(path, headers: true) do |row|
  			additional_information_hash = row.to_hash
			if AdditionalInformation.where("id" => additional_information_hash['id']).exists?
  				additional_information = AdditionalInformation.find_by(id: additional_information_hash['id'])
  			else
  				additional_information = AdditionalInformation.create!(additional_information_hash)
  			end
  			additional_information.update(additional_information_hash)
  		end
  	end
end

zytrip/app/controllers/additional_informations_controller.rb
class AdditionalInformationsController < ApplicationController
  def new
    @additional_information = AdditionalInformation.new
  end

  def create
    @additional_information = AdditionalInformation.new(user_id: current_user.id, slogan: params[:slogan], phone_number: params[:phone_number], instagram_nickname: params[:instagram_nickname], image_url: params[:image_url], description: params[:description])
    
    if !@additional_information.save
      if params[:slogan].length > 30
        flash[:additional_information_error] = "slogan demasiado largo (máximo 30 caracteres)"

      elsif !(params[:phone_number] =~ /[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{2,5}/)
        flash[:additional_information_error] = "Introduzca un nº teléfono válido con formato internacional"

      elsif params[:instagram_nickname].length > 16
        flash[:additional_information_error] = "introduce un usuario de instagram más corto (máximo 15 caracteres)"

      elsif params[:description].length > 250
        flash[:additional_information_error] = "descripción demasiado extensa (máximo 250 caracteres)"
      end
    end

    redirect_to users_profile_path(@additional_information.user_id)

  end

  private

  def additional_information_params
    params.require(:additional_information).permit(:user_id, :slogan, :phone_number, :instagram_nickname, :image_url, :description)
  end

end

zytrip/app/controllers/admin/additional_informations_controller.rb
class Admin::AdditionalInformationsController < ApplicationController

  def index
    unless current_user and current_user.admin?
      redirect_to root_path, error: "You don't belong there"
    end
    
    @additional_informations = AdditionalInformation.all

    respond_to do |format|
      format.html
      format.csv { send_data @additional_informations.to_csv(['id', 'user_id', 'slogan', 'phone_number', 'instagram_nickname', 'image_url', 'description']) }
    end
  end

  def new
    @additional_information = AdditionalInformation.new
  end

  def create
    @additional_information = AdditionalInformation.new(additional_information_params)
    @additional_information.save
    redirect_to admin_additional_informations_path
  end

  def destroy
    @additional_information = AdditionalInformation.find_by(id: params[:id])
    redirect_to admin_additional_informations_path unless @additional_information
    @additional_information.destroy
    redirect_to admin_additional_informations_path
  end

  def edit
    @additional_information = AdditionalInformation.find_by(id: params[:id])
    redirect_to admin_additional_informations_path unless @additional_information
  end

  def update
    @additional_information = AdditionalInformation.find_by(id: params[:id])
    @additional_information.update(additional_information_params)
    redirect_to admin_additional_informations_path
  end

  def import
    AdditionalInformation.import()
    redirect_to admin_additional_informations_path
  end

  private
  
  def additional_information_params
    params.require(:additional_information).permit(:user_id, :slogan, :phone_number, :instagram_nickname, :image_url, :description)
  end
end

zytrip/app/helpers/additional_informations_helper.rb
module AdditionalInformationsHelper
end

zytrip/app/views/admin/additional_informations/_additional_information_form_fields.html.erb
<div class="row">
	<div class="col-md-6 mb-3">
		<%= f.label(:user_id, "Usuario", class:"create-edit-form-label") %>
		<%= f.select(:user_id, options_for_select(User.ids), required: true) %>
	</div>

	<div class="col-md-6 mb-3">
		<%= f.label(:slogan, "¿Cómo te definirías en una palabra?", class:"create-edit-form-label") %>
		<%= f.text_field :slogan, class:"create-edit-form-input", autofocus: true %>
	</div>
</div>

<div class="row">
	<div class="col-md-6 mb-3">
		<%= f.label(:phone_number, "Nº Teléfono", class:"create-edit-form-label") %>
		<%= f.text_field :phone_number, class:"create-edit-form-input", autofocus: true %>
	</div>

	<div class="col-md-6 mb-3">
		<%= f.label(:instagram_nickname, "Instagram", class:"create-edit-form-label") %>
		<%= f.text_field :instagram_nickname, class:"create-edit-form-input", autofocus: true %>
	</div>
</div>

<div class="row">
	<div class="col-md-12 mb-3">
		<%= f.label(:image_url, "¿Quieres tener una imagen de perfil?", class:"create-edit-form-label") %>
		<%= f.text_field :image_url, class:"create-edit-form-input", autofocus: true, placeholder: "copia la dirección URL de la imagen que deseas" %>
	</div>
</div>

<div class="row">
	<div class="col-md-12 mb-3">
		<%= f.label(:description, "Cuéntanos un poco de ti", class:"create-edit-form-label") %>
		<%= f.text_field :description, class:"create-edit-form-input", autofocus: true %>
	</div>
</div>

zytrip/app/views/admin/additional_informations/edit.html.erb
<%= render "layouts/sidebar" %>

<section>
  <div class="create-edit-styled-box">
    <h2 class="create-edit-header">Editar Información Adicional Usuario</h2>
    <%= form_for(@additional_information, url: admin_additional_informations_path(@additional_information)) do |f| %>
      <%= render partial: "additional_information_form_fields", :locals => {:f => f} %>
      <div class="actions-btns">
        <div class="row">
          <div class="col-lg-6 col-md-12 col-sm-12 text-center create-edit-form-cancel-btn">
                <%= link_to "Volver", :back, class: "create-edit-form-cancel-link" %>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 text-center ">
                <%= f.submit "Guardar cambios", class: "create-edit-form-submit-btn" %>
            </div>
          </div>
        </div>
        <% end %>
    </div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "admin" %>
<% end %>

zytrip/app/views/admin/additional_informations/index.html.erb
<%= render "layouts/sidebar" %>

<section>
  <div class="admin-main" id="users">

    <div class="admin-new-panel">
      <div class="row ">
        <div class="col-6 admin-model-title">
          <strong>Información Adicional Usuarios</strong>
        </div>

        <div class="col-6">
          <%= form_tag import_admin_additional_informations_path, multipart: true, class: "form-inline" do %>
            <div class="row">
              <div class="col import-form-btn text-center">
                <%= link_to "Añadir información", new_admin_additional_information_path, class: "import-form-btn-link" %>
              </div>
              <div class="col import-form-btn text-center">
                <%= link_to "Exportar CSV", admin_additional_informations_path(format: :csv), class: "import-form-btn-link" %>
              </div>
              <div class="col text-center">
                <%= submit_tag "Importar informaciones", class:"import-form-submit-btn" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <table class="admin-model-table">
      <thead>
        <tr>
          <th>ID Información</th>
          <th>ID Usuario</th>
          <th>Slogan</th>
          <th>Nº Teléfono</th>
          <th>Instagram</th>
          <th>Administración</th>
        </tr>
      </thead>

      <tbody>
        <% @additional_informations.each do |additional_information| %>
          <tr>
            <td><%= additional_information.id %></td>
            <td><%= additional_information.user_id %></td>
            <td><%= additional_information.slogan %></td>
            <td><%= additional_information.phone_number %></td>
            <td><%= additional_information.instagram_nickname %></td>
            <td>
              <div class="row justify-content-center">
                <div class="col-2">
                  <%= link_to edit_admin_additional_information_path(additional_information), title:"Editar" do %>
                    <i class="fas fa-briefcase"></i>
                  <% end %>
                </div>

                <div class="col-2">
                  <%= button_to admin_additional_information_path(additional_information), method: :delete, class:"admin-delete-button", title:"Eliminar" do %> 
                    <i class="fas fa-briefcase admin-delete"></i>
                  <% end %>
                </div>
              </div>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "admin" %>
<% end %>

zytrip/app/views/admin/additional_informations/new.html.erb
<%= render "layouts/sidebar" %>
<section>
  <div class="create-edit-styled-box">
    <h2 class="create-edit-header">Crear Información Adicional Usuarios</h2>
    <%= form_for(@additional_information, url: admin_additional_informations_path(@additional_information)) do |f| %>
      <%= render partial: "additional_information_form_fields", :locals => {:f => f} %>
      <div class="actions-btns">
        <div class="row">
          <div class="col-lg-6 col-md-12 col-sm-12 text-center create-edit-form-cancel-btn">
                <%= link_to "Volver", :back, class: "create-edit-form-cancel-link" %>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 text-center ">
                <%= f.submit "Crear", class: "create-edit-form-submit-btn" %>
            </div>
          </div>
        </div>
        <% end %>
    </div>
</section>

<% content_for :view_specific_css do %>
    <%= stylesheet_link_tag "admin" %>
<% end %>